tapir/log/urls.py
from django.urls import path

from tapir.log import views

app_name = "log"
urlpatterns = [
    path(
        "<int:pk>/email_content",
        views.email_log_entry_content,
        name="email_log_entry_content",
    ),
    path(
        "text/create/<str:member_type>/<int:member_pk>",
        views.create_text_log_entry,
        name="create_text_log_entry",
    ),
    path(
        "log_overview",
        views.LogTableView.as_view(),
        name="log_overview",
    ),
]

tapir/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import generic

from tapir.settings import ENABLE_SILK_PROFILING

urlpatterns = [
    path("", generic.RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL)),
    path("admin/", admin.site.urls),
    path("accounts/", include("tapir.accounts.urls")),
    path("shifts/", include("tapir.shifts.urls")),
    path("rizoma/", include("tapir.rizoma.urls")),
    path("coop/", include("tapir.coop.urls")),
    path("log/", include("tapir.log.urls")),
    path("core/", include("tapir.core.urls")),
    path("statistics/", include("tapir.statistics.urls")),
    path("welcomedesk/", include("tapir.welcomedesk.urls")),
    path("financingcampaign/", include("tapir.financingcampaign.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if ENABLE_SILK_PROFILING:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

tapir/log/models.py
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import HStoreField
from django.contrib.postgres.indexes import GinIndex
from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.db import models
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _

from tapir.log.util import freeze_for_log


class LogEntry(models.Model):
    class Meta:
        indexes = [
            models.Index(fields=["user"]),
            models.Index(fields=["share_owner"]),
            models.Index(fields=["created_date"]),
        ]

    created_date = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Creation Date")
    )

    actor = models.ForeignKey(
        "accounts.TapirUser", null=True, on_delete=models.SET_NULL, related_name="+"
    )

    # User or ShareOwner that this log entry is associated with. Exactly one should be filled
    user = models.ForeignKey(
        "accounts.TapirUser",
        related_name="log_entries",
        null=True,
        on_delete=models.CASCADE,
    )
    share_owner = models.ForeignKey(
        "coop.ShareOwner",
        related_name="log_entries",
        null=True,
        on_delete=models.CASCADE,
    )

    log_class_type = models.ForeignKey(
        ContentType, on_delete=models.PROTECT, related_name="+"
    )

    # Not abstract to be able to query all log entries, see https://stackoverflow.com/questions/3797982/how-to-query-abstract-class-based-objects-in-django

    def clean(self):
        super().clean()
        if bool(self.user) == bool(self.share_owner):
            raise ValidationError("Exactly one of user and share_owner must be set.")

    def save(self, *args, **kwargs):
        if not hasattr(self, "log_class_type"):
            # for_concrete_model=False makes this also works for proxy models (that don't add any fields themselves
            # but just add rendering)
            self.log_class_type = ContentType.objects.get_for_model(
                self.__class__, for_concrete_model=False
            )

        super(LogEntry, self).save(*args, **kwargs)

    def as_leaf_class(self):
        """
        Returns the log entry as it was when being saved to the database

        Since log entries derive from LogEntry, but access is done via the LogEntry class,
        we need to retrieve the original log entry from its original model which is saved
        as log_class_type.
        """
        if not self.log_class_type:
            return self

        model_class = self.log_class_type.model_class()
        if model_class:
            return model_class.objects.get(pk=self.pk)
        else:
            return self

    def populate_base(self, actor=None, tapir_user=None, share_owner=None):
        """Populate the log entry model fields.

        This should be used instead of the normal model creation mechanism to do event-specific info extraction logic
        to be done in the log entry class instead of the call sites. For example, for a LogEntry subclass recording an
        email that was sent, callers should only have to pass in the email, how that email should be saved is decided
        by the log entry class instead."""

        self.actor = actor
        self.user = tapir_user
        self.share_owner = share_owner

        if self.share_owner and hasattr(self.share_owner, "user"):
            self.user = self.share_owner.user

        # Prefer user over share_owner
        if self.share_owner and self.user:
            self.share_owner = None

        return self

    def get_context_data(self):
        """Return the context data for the template rendering this LogEntry."""
        return {"entry": self}

    def render(self):
        """Render this LogEntry"""
        return render_to_string(self.template_name, self.get_context_data())

    @classmethod
    def verbose_log_name(cls):
        return cls._meta.verbose_name.title()


class EmailLogEntry(LogEntry):
    """EmailLogEntry logs a sent email message."""

    template_name = "log/email_log_entry.html"

    email_id = models.CharField(
        max_length=128, null=False, blank=False, default="unknown"
    )
    subject = models.CharField(max_length=128, null=True, blank=True)
    email_content = models.BinaryField(null=True)

    def populate(
        self,
        email_id: str,
        email_message: EmailMessage,
        actor=None,
        tapir_user=None,
        share_owner=None,
    ):
        self.email_id = email_id
        if email_message is not None:
            self.subject = email_message.subject[:128]
            self.email_content = email_message.message().as_bytes()
        return super().populate_base(
            actor=actor, tapir_user=tapir_user, share_owner=share_owner
        )

    def get_name(self) -> str:
        # Must import locally to avoid import loop.
        from tapir.core.tapir_email_builder_base import all_emails

        if self.email_id is not None and self.email_id in all_emails.keys():
            return all_emails[self.email_id].get_name()
        return _("Not available")


class TextLogEntry(LogEntry):
    """TextLogEntry logs a manual textual notes.

    This entry type should only be used for manual, user-entered text. For log entries created as a side effect of
    another action, please create an event-specific LogEntry.
    """

    template_name = "log/text_log_entry.html"

    text = models.TextField(blank=False)

    def populate(self, actor, share_owner=None, tapir_user=None):
        # The value for the text field is set by a CreateTextLogEntryForm
        return super().populate_base(
            actor=actor, share_owner=share_owner, tapir_user=tapir_user
        )


class UpdateModelLogEntry(LogEntry):
    old_values = HStoreField()
    new_values = HStoreField()

    class Meta:
        abstract = True
        indexes = [
            GinIndex(
                fields=["old_values"],
            ),
            GinIndex(
                fields=["new_values"],
            ),
        ]

    def populate_base(
        self,
        actor=None,
        tapir_user=None,
        share_owner=None,
        old_frozen: dict | None = None,
        new_frozen: dict | None = None,
        old_model=None,
        new_model=None,
    ):
        if old_model:
            old_frozen = freeze_for_log(old_model)
        if new_model:
            new_frozen = freeze_for_log(new_model)

        # List must not change during iteration
        keys = list(old_frozen.keys())
        # Only record changed
        for k in keys:
            if old_frozen.get(k, None) != new_frozen.get(k, None):
                # HStoreField stores strings only
                old_frozen[k] = str(old_frozen[k])
                new_frozen[k] = str(new_frozen[k])
            else:
                del old_frozen[k]
                del new_frozen[k]

        self.old_values = old_frozen
        self.new_values = new_frozen

        return super().populate_base(
            actor=actor, tapir_user=tapir_user, share_owner=share_owner
        )

    def get_context_data(self):
        context = super().get_context_data()

        changes = []
        for k in self.old_values.keys():
            if hasattr(self, "excluded_fields") and k in self.excluded_fields:
                continue
            changes.append((k, self.old_values[k], self.new_values[k]))
        context["changes"] = changes

        return context


class ModelLogEntry(LogEntry):
    values = HStoreField()

    class Meta:
        abstract = True

    def populate_base(
        self,
        actor=None,
        share_owner=None,
        tapir_user=None,
        frozen=None,
        model=None,
    ):
        frozen = freeze_for_log(model) if model else frozen

        if hasattr(self, "exclude_fields"):
            for k in self.exclude_fields:
                del frozen[k]

        self.values = frozen
        return super().populate_base(
            actor=actor, share_owner=share_owner, tapir_user=tapir_user
        )

    def get_context_data(self):
        context = super().get_context_data()
        context["values"] = (
            self.values.items() if hasattr(self.values, "items") else self.values
        )
        return context

tapir/log/forms.py
from django.forms import ModelForm, TextInput

from tapir.log.models import TextLogEntry


class CreateTextLogEntryForm(ModelForm):
    class Meta:
        model = TextLogEntry
        fields = ["text"]
        widgets = {
            "text": TextInput(),
        }

tapir/log/views.py
import datetime

import django_filters
import django_tables2
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q, QuerySet
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.utils.translation import gettext_lazy as _
from django.views.decorators.http import require_GET, require_POST
from django_filters import DateRangeFilter
from django_filters.views import FilterView
from django_tables2.views import SingleTableView

from tapir.accounts.models import TapirUser
from tapir.coop.models import ShareOwner
from tapir.core.config import TAPIR_TABLE_CLASSES, TAPIR_TABLE_TEMPLATE
from tapir.log.forms import CreateTextLogEntryForm
from tapir.log.models import EmailLogEntry, TextLogEntry, LogEntry
from tapir.log.util import freeze_for_log
from tapir.settings import PERMISSION_COOP_MANAGE, PERMISSION_COOP_VIEW
from tapir.utils.filters import TapirUserModelChoiceFilter, ShareOwnerModelChoiceFilter
from tapir.utils.shortcuts import (
    safe_redirect,
    set_header_for_file_download,
)
from tapir.utils.user_utils import UserUtils


@require_GET
@login_required
@permission_required(PERMISSION_COOP_MANAGE)
def email_log_entry_content(request, pk):
    log_entry = get_object_or_404(EmailLogEntry, pk=pk)
    filename = "tapir_email_{}_{}.eml".format(
        log_entry.user.username if log_entry.user else str(log_entry.share_owner.id),
        log_entry.created_date.strftime("%Y-%m-%d_%H-%M-%S"),
    )

    response = HttpResponse(content_type="application/octet-stream")
    set_header_for_file_download(response, filename)
    response.write(log_entry.email_content)
    return response


class UpdateViewLogMixin:
    def get_object(self, *args, **kwargs):
        result = super().get_object(*args, **kwargs)
        self.old_object_frozen = freeze_for_log(result)
        return result


@require_POST
@login_required
@permission_required(PERMISSION_COOP_MANAGE)
def create_text_log_entry(request, **kwargs):
    member_type = kwargs.get("member_type")
    member_id = kwargs.get("member_pk")

    if member_type == "tapir_user":
        member = TapirUser.objects.get(id=member_id)
        log_entry = TextLogEntry().populate(actor=request.user, tapir_user=member)
    else:
        member = ShareOwner.objects.get(id=member_id)
        log_entry = TextLogEntry().populate(actor=request.user, share_owner=member)

    form = CreateTextLogEntryForm(request.POST, instance=log_entry)

    if not form.is_valid():
        return HttpResponseBadRequest(str(form.errors))

    form.save()

    return safe_redirect(member.get_absolute_url(), "/", request)


class LogTable(django_tables2.Table):
    class Meta:
        model = LogEntry
        template_name = TAPIR_TABLE_TEMPLATE
        fields = ["created_date", "actor", "member", "entry"]
        order_by = "-created_date"
        attrs = {"class": TAPIR_TABLE_CLASSES}

    entry = django_tables2.Column(
        empty_values=(),
        accessor="as_leaf_class__render",
        verbose_name=_("Message"),
        orderable=False,
    )
    member = django_tables2.Column(
        empty_values=(), accessor="user", verbose_name=_("Member")
    )

    actor = django_tables2.Column(verbose_name=_("Actor"))

    def before_render(self, request):
        self.request = request

    def render_created_date(self, value: datetime.datetime):
        return value.strftime("%d.%m.%Y %H:%M")

    def render_member(self, record):
        # show user or share_owner, depending on what is available
        person = record.user or record.share_owner.get_info()
        return UserUtils.build_html_link_for_viewer(person, self.request.user)

    def render_actor(self, value: TapirUser):
        return UserUtils.build_html_link_for_viewer(value, self.request.user)


class LogFilter(django_filters.FilterSet):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        share_owners = self.filters["members"].field.queryset
        tapir_users = self.filters["actor"].field.queryset
        if self.request.user.has_perm(PERMISSION_COOP_VIEW):
            # In case the user who requests the Logs actually has permission, make a list of all ShareOwners
            share_owners = share_owners.order_by("id")
        else:
            share_owners = share_owners.filter(id=self.request.user.share_owner.id)
            tapir_users = tapir_users.filter(pk=self.request.user.pk)
        self.filters["members"].field.queryset = share_owners
        self.filters["actor"].field.queryset = tapir_users.filter(
            id__in=LogEntry.objects.filter(user_id__in=tapir_users)
            .values_list("actor", flat=True)
            .distinct()
        )
        # Second Method
        self.filters["log_class_type__model"].extra.update(
            {
                "choices": tuple(
                    [
                        (
                            item.model,
                            item.model_class().verbose_log_name(),
                        )
                        for item in ContentType.objects.filter(
                            id__in=LogEntry.objects.values_list(
                                "log_class_type", flat=True
                            ).distinct()
                        )
                    ]
                )
            }
        )

    time = DateRangeFilter(field_name="created_date")
    actor = TapirUserModelChoiceFilter(label=_("Actor"))
    members = ShareOwnerModelChoiceFilter(method="member_filter", label=_("Member"))
    log_class_type__model = django_filters.ChoiceFilter(label=_("Log Type"))

    def member_filter(self, queryset: QuerySet, name, value: ShareOwner):
        # check if value is either in user or share_owner (can only be in one)
        return queryset.filter(
            Q(share_owner__id=value.id) | Q(user__share_owner=value.id)
        )

    class Meta:
        model = LogEntry
        fields = []


class LogTableView(LoginRequiredMixin, FilterView, SingleTableView):
    model = LogEntry
    table_class = LogTable
    template_name = "log/log_overview.html"

    filterset_class = LogFilter

    def get_queryset(self):
        queryset = (
            LogEntry.objects.all()
            .prefetch_related("actor")
            .prefetch_related("user")
            .prefetch_related("share_owner")
            .prefetch_related("share_owner__user")
            .prefetch_related("log_class_type")
        )
        if not self.request.user.has_perm(PERMISSION_COOP_VIEW):
            return queryset.filter(user=self.request.user)
        return queryset

tapir/log/templates/log/email_log_entry.html
{% load i18n %}
{% load core %}
{% translate "Email sent." %}
<br />
Name : {{ entry.get_name }}
<br />
Subject : {{ entry.subject }}
<br />
{% if entry.email_content %}
    <a class="{% tapir_button_link %} btn-sm"
       href="{% url 'log:email_log_entry_content' entry.pk %}">
        <span class="material-icons">download</span>
        Download
    </a>
{% else %}
    {% translate "Email-Inhalt ist aus Sicherheitsgründen nicht verfügbar" %}
{% endif %}

tapir/log/templates/log/log_entry_list_tag.html
{% load i18n %}
{% load django_bootstrap5 %}
{% load tapir_log %}
{% load core %}
{% load utils %}
<div class="card mb-2">
    <h5 class="card-header d-flex justify-content-between align-items-center flex-wrap gap-2">
        {% translate "Last 5 log entries" %}
        <span class="d-flex justify-content-end flex-fill flex-wrap gap-2">
            <a class="{% tapir_button_link %}"
               href="{% url 'log:log_overview' %}?members={{ share_owner_id }}">
                <span class="material-icons">manage_search</span>
                {% translate 'See all log entries' %}
            </a>
        </span>
    </h5>
    <div class="card-body">
        <div class="table-responsive">
            <table class="{% tapir_table_classes %} table-sm"
                   aria-label="{% translate 'List of log entries for this member' %}">
                <thead>
                    <tr>
                        <th scope="col">{% translate 'Date' %}</th>
                        <th scope="col">{% translate 'Actor' %}</th>
                        <th scope="col">{% translate 'Message' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for o in log_entries %}
                        <tr>
                            <td>{{ o.created_date|date:"d.m.Y H:i" }}</td>
                            <td>
                                {% if o.actor %}
                                    {% get_display_name_for_viewer o.actor request.user %}
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                            <td>{{ o.render }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% if perms.accounts.manage %}
            <form method="post" action="{{ create_text_log_entry_action_url }}">
                {% csrf_token %}
                {% comment %}
                    Ideally we would let the form field render itself here, but it's easier to style as
                    an inline field
                    this way.
                {% endcomment %}
                <div class="d-flex flex-wrap justify-content-end">
                    <input class="form-control m-1"
                           name="text"
                           aria-label="{% translate 'Notes about this user' %}"
                           placeholder="{% translate 'Notes about this user' %}">
                    <button class="{% tapir_button_action %}"
                            type="submit"
                            id="add_note_button"
                            style="min-width: 100px">
                        <span class="material-icons">note</span>{% translate "Add Note" %}
                    </button>
                </div>
            </form>
        {% endif %}
    </div>
</div>

tapir/log/templates/log/log_overview.html
{% extends "core/base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load coop %}
{% load static %}
{% load render_table from django_tables2 %}
{% load core %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "coop/css/coop.css" %}">
    <style>
        .select2 {    
            width: 100%!important; /* overrides computed width, 100px in your demo */ 
        }
    </style>
    {{ filter.form.media }}
{% endblock head %}
{% block content %}
    <div class="card m-2">
        <div class="card-header">
            <div class="d-flex flex-row justify-content-between">
                <div class="col-6 d-flex flex-column justify-content-center">
                    <h5 style="margin-bottom: 0">
                        <span>{% translate "Logs" %}</span>
                    </h5>
                </div>
                <div class="col-6 d-flex justify-content-end">
                    <button class="{% tapir_button_link_to_action %}"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#collapseFilter"
                            aria-expanded="false"
                            aria-controls="collapseFilter">
                        {% translate "Filters" %}
                        <span class="material-icons">unfold_more</span>
                    </button>
                </div>
            </div>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item collapse" id="collapseFilter">
                {% if filter %}
                    <form action="" method="get" class="form log-filter-form">
                        {% bootstrap_form filter.form %}
                        <button class="{% tapir_button_link %}">
                            <span class="material-icons">filter_alt</span>{% translate 'Filter' %}
                        </button>
                    </form>
                {% endif %}
            </li>
            <li class="list-group-item">{% render_table table %}</li>
        </ul>
    </div>
{% endblock content %}

tapir/log/templates/log/text_log_entry.html
{{ entry.text }}