tapir/shifts/urls.py
from django.urls import path

from tapir.shifts import views

app_name = "shifts"
urlpatterns = [
    path("shift/<int:pk>/", views.ShiftDetailView.as_view(), name="shift_detail"),
    path(
        "shift/<int:pk>/printable",
        views.ShiftDetailView.as_view(
            template_name="shifts/shift_detail_printable.html"
        ),
        name="shift_detail_printable",
    ),
    path(
        "shift/<str:day>/day_printable",
        views.ShiftDayPrintableView.as_view(),
        name="shift_day_printable",
    ),
    path(
        "shift/<str:day>/day_cancel",
        views.CancelDayShiftsView.as_view(),
        name="shift_day_cancel",
    ),
    path(
        "shift/<int:pk>/edit",
        views.EditShiftView.as_view(),
        name="shift_edit",
    ),
    path(
        "shift/<int:pk>/delete",
        views.DeleteShiftView.as_view(),
        name="shift_delete",
    ),
    path(
        "shift_template/<int:pk>/edit",
        views.EditShiftTemplateView.as_view(),
        name="shift_template_edit",
    ),
    path(
        "shift_template/create",
        views.ShiftTemplateCreateView.as_view(),
        name="shift_template_create",
    ),
    path(
        "shift_attendance/<int:pk>/<int:state>",
        views.UpdateShiftAttendanceStateView.as_view(),
        name="update_shift_attendance_state",
    ),
    path(
        "shift_attendance_form/<int:pk>/<int:state>",
        views.UpdateShiftAttendanceStateWithFormView.as_view(),
        name="update_shift_attendance_state_with_form",
    ),
    path(
        "shifttemplate/<int:pk>",
        views.ShiftTemplateDetail.as_view(),
        name="shift_template_detail",
    ),
    path(
        "shift_template_duplicate/<int:shift_pk>/create",
        views.ShiftTemplateDuplicateView.as_view(),
        name="shift_template_duplicate",
    ),
    path(
        "shifttemplate/overview",
        views.ShiftTemplateOverview.as_view(),
        name="shift_template_overview",
    ),
    path(
        "slottemplate/<int:slot_template_pk>/register",
        views.RegisterUserToShiftSlotTemplateView.as_view(),
        name="slottemplate_register",
    ),
    path(
        "shiftslot/<int:slot_pk>/register/",
        views.RegisterUserToShiftSlotView.as_view(),
        name="slot_register",
    ),
    path(
        "shift_attendance_template/<int:pk>/delete",
        views.shift_attendance_template_delete,
        name="shift_attendance_template_delete",
    ),
    path(
        "calendar",
        views.ShiftCalendarView.as_view(),
        name="calendar",
    ),
    path(
        "shift_user_data/<int:pk>",
        views.EditShiftUserDataView.as_view(),
        name="edit_shift_user_data",
    ),
    path(
        "group_calendar",
        views.ShiftTemplateGroupCalendar.as_view(),
        name="shift_template_group_calendar",
    ),
    path(
        "group_calendar/<int:year>",
        views.ShiftTemplateGroupCalendar.as_view(),
        name="shift_template_group_calendar",
    ),
    path(
        "group_calendar/<int:year>/pdf",
        views.ShiftTemplateGroupCalendarAsPdf.as_view(),
        name="calendarpdf",
    ),
    path(
        "shift_account_entry/log/<int:user_pk>",
        views.UserShiftAccountLog.as_view(),
        name="user_shift_account_log",
    ),
    path(
        "shift_account_entry/create/<int:user_pk>",
        views.CreateShiftAccountEntryView.as_view(),
        name="create_shift_account_entry",
    ),
    path(
        "shift_exemption/create/<int:shift_user_data_pk>",
        views.CreateShiftExemptionView.as_view(),
        name="create_shift_exemption",
    ),
    path(
        "shift_exemption/<int:pk>/edit",
        views.EditShiftExemptionView.as_view(),
        name="edit_shift_exemption",
    ),
    path(
        "shift_exemption",
        views.ShiftExemptionListView.as_view(),
        name="shift_exemption_list",
    ),
    path(
        "members_on_alert",
        views.MembersOnAlertView.as_view(),
        name="members_on_alert",
    ),
    path(
        "shift/<int:pk>/cancel",
        views.CancelShiftView.as_view(),
        name="cancel_shift",
    ),
    path(
        "shift/create",
        views.ShiftCreateView.as_view(),
        name="create_shift",
    ),
    path(
        "shift/<int:shift_pk>/slot/create",
        views.ShiftSlotCreateView.as_view(),
        name="create_slot",
    ),
    path(
        "shift_template/<int:shift_pk>/slot_template/create",
        views.ShiftSlotTemplateCreateView.as_view(),
        name="create_slot_template",
    ),
    path(
        "slot/<int:pk>/edit",
        views.ShiftSlotEditView.as_view(),
        name="edit_slot",
    ),
    path(
        "slot_template/<int:pk>/edit",
        views.ShiftSlotTemplateEditView.as_view(),
        name="edit_slot_template",
    ),
    path(
        "management",
        views.ShiftManagementView.as_view(),
        name="shift_management",
    ),
    path(
        "run_freeze_checks_manually",
        views.RunFreezeChecksManuallyView.as_view(),
        name="run_freeze_checks_manually",
    ),
    path(
        "generate_shifts_manually",
        views.GenerateShiftsManuallyView.as_view(),
        name="generate_shifts_manually",
    ),
    path(
        "convert_shift_exemption_to_membership_pause/<int:pk>",
        views.ConvertShiftExemptionToMembershipPauseView.as_view(),
        name="convert_shift_exemption_to_membership_pause",
    ),
    path(
        "solidarity_shift_used/<int:pk>",
        views.SolidarityShiftUsed.as_view(),
        name="solidarity_shift_used",
    ),
    path(
        "solidarity_shift_given/<int:pk>",
        views.SolidarityShiftGiven.as_view(),
        name="solidarity_shift_given",
    ),
    path(
        "solidarity_shifts",
        views.SolidarityShiftsView.as_view(),
        name="solidarity_shifts",
    ),
    path(
        "solidarity_shifts/gifted_solidarity_shifts_json",
        views.GiftedSolidarityShiftsJsonView.as_view(),
        name="gifted_solidarity_shifts_json",
    ),
    path(
        "solidarity_shifts/used_solidarity_shifts_json",
        views.UsedSolidarityShiftsJsonView.as_view(),
        name="used_solidarity_shifts_json",
    ),
    path(
        "attendance/<int:pk>/custom_time",
        views.UpdateShiftAttendanceCustomTimeView.as_view(),
        name="attendance_custom_time",
    ),
    path(
        "attendance_template/<int:pk>/custom_time",
        views.UpdateShiftAttendanceTemplateCustomTimeView.as_view(),
        name="attendance_template_custom_time",
    ),
    path(
        "watch_shift/<int:shift>/", views.WatchShiftView.as_view(), name="watch_shift"
    ),
    path(
        "unwatch_shift/<int:shift>/",
        views.UnwatchShiftView.as_view(),
        name="unwatch_shift",
    ),
    path(
        "create_watch_recurring_shifts/<int:pk>",
        views.CreateRecurringShiftWatchView.as_view(),
        name="create_watch_recurring_shifts",
    ),
    path(
        "shiftwatch_overview/<int:pk>",
        views.RecurringShiftwatchListView.as_view(),
        name="shiftwatch_overview",
    ),
]

tapir/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import generic

from tapir.settings import ENABLE_SILK_PROFILING

urlpatterns = [
    path("", generic.RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL)),
    path("admin/", admin.site.urls),
    path("accounts/", include("tapir.accounts.urls")),
    path("shifts/", include("tapir.shifts.urls")),
    path("rizoma/", include("tapir.rizoma.urls")),
    path("coop/", include("tapir.coop.urls")),
    path("log/", include("tapir.log.urls")),
    path("core/", include("tapir.core.urls")),
    path("statistics/", include("tapir.statistics.urls")),
    path("welcomedesk/", include("tapir.welcomedesk.urls")),
    path("financingcampaign/", include("tapir.financingcampaign.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if ENABLE_SILK_PROFILING:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

tapir/shifts/views/calendars.py
import datetime
from calendar import MONDAY
from collections import OrderedDict

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import OuterRef, Exists
from django.http import HttpResponse
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.views.generic import TemplateView
from weasyprint import HTML

from tapir.coop.pdfs import CONTENT_TYPE_PDF
from tapir.shifts.models import (
    Shift,
    WEEKDAY_CHOICES,
    ShiftTemplateGroup,
    ShiftTemplate,
)
from tapir.shifts.templatetags.shifts import get_week_group, user_watching_shift
from tapir.shifts.utils import ColorHTMLCalendar
from tapir.shifts.views.views import get_shift_slot_names, SelectedUserViewMixin
from tapir.utils.shortcuts import get_monday, set_header_for_file_download


class ShiftCalendarView(LoginRequiredMixin, TemplateView):
    template_name = "shifts/shift_calendar_future.html"
    DATE_FORMAT = "%Y-%m-%d"

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)

        date_from = (
            datetime.datetime.strptime(
                self.request.GET["date_from"], self.DATE_FORMAT
            ).date()
            if "date_from" in self.request.GET.keys()
            else timezone.now().date()
        )
        date_to = (
            datetime.datetime.strptime(
                self.request.GET["date_to"], self.DATE_FORMAT
            ).date()
            if "date_to" in self.request.GET.keys()
            else date_from + datetime.timedelta(days=60)
        )
        context_data["date_from"] = date_from.strftime(self.DATE_FORMAT)
        context_data["date_to"] = date_to.strftime(self.DATE_FORMAT)

        context_data["nb_days_for_self_unregister"] = Shift.NB_DAYS_FOR_SELF_UNREGISTER
        # Because the shift views show a lot of shifts,
        # we preload all related objects to avoid doing many database requests.
        user_watching = user_watching_shift(
            user=self.request.user, shift=OuterRef("pk")
        )
        shifts = (
            Shift.objects.prefetch_related("slots")
            .prefetch_related("slots__attendances")
            .prefetch_related("slots__attendances__user")
            .prefetch_related("slots__slot_template")
            .prefetch_related("slots__slot_template__attendance_template")
            .prefetch_related("slots__slot_template__attendance_template__user")
            .prefetch_related("shift_template")
            .prefetch_related("shift_template__group")
            .filter(
                start_time__date__gte=date_from,
                start_time__date__lt=date_to + datetime.timedelta(days=1),
                deleted=False,
            )
            .annotate(is_watching=Exists(user_watching))
            .order_by("start_time")
        )

        # A nested dict containing weeks (indexed by the Monday of the week), then days, then a list of shifts
        # OrderedDict[OrderedDict[list]]
        shifts_by_weeks_and_days = OrderedDict()
        week_to_group = {}
        for shift in shifts:
            shift_day = shift.start_time.date()
            shift_week_monday = shift_day - datetime.timedelta(days=shift_day.weekday())

            # Ensure the nested OrderedDict[OrderedDict[list]] dictionary has the right data structures for the new item
            shifts_by_weeks_and_days.setdefault(shift_week_monday, OrderedDict())
            shifts_by_weeks_and_days[shift_week_monday].setdefault(shift_day, [])

            shifts_by_weeks_and_days[shift_week_monday][shift_day].append(shift)
            if shift.shift_template is not None:
                week_to_group[shift_week_monday] = shift.shift_template.group

        context_data["shifts_by_weeks_and_days"] = shifts_by_weeks_and_days
        context_data["shift_slot_names"] = get_shift_slot_names()
        context_data["week_to_group"] = week_to_group

        return context_data


class ShiftTemplateOverview(LoginRequiredMixin, SelectedUserViewMixin, TemplateView):
    template_name = "shifts/shift_template_overview.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        grouped_per_day = {}
        for weekday in WEEKDAY_CHOICES:
            grouped_per_day[weekday[1]] = OrderedDict()

        groups_ordered_by_name = ShiftTemplateGroup.objects.all().order_by("name")

        for t in (
            ShiftTemplate.objects.all()
            .order_by("start_time")
            .prefetch_related("group")
            .prefetch_related("slot_templates")
            .prefetch_related("slot_templates__attendance_template")
        ):
            template: ShiftTemplate = t
            weekday_group = grouped_per_day[WEEKDAY_CHOICES[template.weekday][1]]
            start_time_as_string = str(template.start_time)
            if start_time_as_string not in weekday_group:
                weekday_group[start_time_as_string] = {}
            time_group = weekday_group[start_time_as_string]
            if template.group.name not in time_group:
                for template_group in groups_ordered_by_name:
                    time_group[template_group.name] = {}
            for template_group in groups_ordered_by_name:
                if template.name not in time_group[template_group.name]:
                    time_group[template_group.name][template.name] = None
            template_group_group = time_group[template.group.name]
            template_group_group[template.name] = template

        context["day_groups"] = grouped_per_day
        context["shift_template_groups"] = [
            group.name for group in ShiftTemplateGroup.objects.all().order_by("name")
        ]
        context["shift_slot_names"] = get_shift_slot_names()
        return context


class ShiftTemplateGroupCalendar(LoginRequiredMixin, TemplateView):
    template_name = "shifts/shift_template_group_calendar.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        displayed_year = self.kwargs.get("year", timezone.now().date().year)

        monday_to_week_group_map = {}
        current_monday = get_monday(datetime.date(year=displayed_year, month=1, day=1))
        shift_groups_count = ShiftTemplateGroup.objects.count()
        while current_monday.year <= displayed_year:
            monday_to_week_group_map[current_monday] = get_week_group(
                current_monday, shift_groups_count=shift_groups_count
            ).name
            current_monday += datetime.timedelta(days=7)

        colored_calendar = ColorHTMLCalendar(
            firstweekday=MONDAY, monday_to_week_group_map=monday_to_week_group_map
        )
        rendered_calendar = colored_calendar.formatyear(theyear=displayed_year, width=4)

        context["rendered_calendar"] = mark_safe(rendered_calendar)
        context["displayed_year"] = displayed_year

        return context


class ShiftTemplateGroupCalendarAsPdf(ShiftTemplateGroupCalendar):
    def get_context_data(self, *args, **kwargs):
        return super().get_context_data(*args, **kwargs)

    def get(self, *args, **kwargs):
        context = self.get_context_data()
        response = HttpResponse(content_type=CONTENT_TYPE_PDF)
        set_header_for_file_download(
            response, f"shiftcalendar_{context['displayed_year']}"
        )
        html = context["rendered_calendar"]
        HTML(string=html).write_pdf(
            response, stylesheets=["tapir/shifts/static/shifts/css/calendar.css"]
        )
        return response

tapir/shifts/templates/shifts/cancel_shift.html
{% extends "core/base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load static %}
{% load core %}
{% block title %}
    {% translate "Cancel shift:" %} {{ form.instance }}
{% endblock title %}
{% block content %}
    <div class="container">
        <div class="card mb-2">
            <h5 class="card-header bg-warning">
                {% translate "Cancel entire shift:" %} <a href="{{ form.instance.get_absolute_url }}">{{ form.instance }}</a>
            </h5>
            <div class="card-body">
                <div>
                    <p>
                        {% blocktranslate %}
                            This will cancel the entire shift for that day. It will not affect other shifts that come from
                            the same ABCD shift.
                        {% endblocktranslate %}
                    </p>
                    <p>
                        {% blocktranslate %}
                            Cancelling a shift is used for example for holidays. It has the following consequences :
                            <ul>
                                <li>It is not possible to register to the shift anymore.</li>
                                <li>Members who are registered from their ABCD shift get a shift point.</li>
                                <li>Members who registered just to this shift don't get a point.</li>
                            </ul>
                        {% endblocktranslate %}
                    </p>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="d-flex justify-content-end">
                        <button type="submit" class="{% tapir_button_action %}">
                            <span class="material-icons">cancel</span>
                            {% translate 'Confirm cancellation' %}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

tapir/shifts/templates/shifts/exemption_table_actions_column.html
{% load core %}
<span class="d-flex flex-row gap-2">
    <a href="{% url "shifts:edit_shift_exemption" pk=record.pk %}"
       class="{% tapir_button_link_to_action %}">
        <span class="material-icons">edit</span>
        <span>Edit</span>
    </a>
    <a href="{% url "shifts:convert_shift_exemption_to_membership_pause" pk=record.pk %}"
       class="{% tapir_button_action %}">
        <span class="material-icons">pause</span>
        <span>Convert to membership pause</span>
    </a>
</span>

tapir/shifts/templates/shifts/shift_calendar_template.html
{% extends "shifts/base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load shifts %}
{% load i18n %}
{% load core %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'shifts/css/shifts.css' %}">
    <script src="{% static 'shifts/ShiftFiltersManager.js' %}?version=2" defer></script>
    <script>
        function onFilter() {
            let url = "{% url "shifts:calendar" %}";
            url += "?date_from=" + document.getElementById("date-from").value;
            url += "&date_to=" + document.getElementById("date-to").value;
            window.location = url;
        }
    </script>
{% endblock head %}
{% block content %}
    <div class="d-flex align-items-center justify-content-end m-2">
        <a class="{% tapir_button_link %} me-2"
           href="{% url 'shifts:shift_template_group_calendar' %}">
            <span class="material-icons">table_view</span>
            {% translate "ABCD annual calendar" %}
        </a>
        <button class="{% tapir_button_link %}"
                data-bs-toggle="collapse"
                data-bs-target="#collapseCalendarInfo"
                aria-expanded="false"
                style="text-decoration: none">
            <span class="material-icons">unfold_more</span>{% translate "Legend & Filters" %}
        </button>
    </div>
    <div class="collapse" id="collapseCalendarInfo">
        <div class="card-group mb-2">
            <div class="card">
                <h5 class="card-header">
                    {% block card_title %}
                    {% endblock card_title %}
                </h5>
                <div class="card-body">
                    {% block card_helptext %}
                    {% endblock card_helptext %}
                </div>
            </div>
            {% shift_filters %}
        </div>
    </div>
    {% for week, shifts_by_day in shifts_by_weeks_and_days.items %}
        <div class="card mb-2">
            {% with week_group=week_to_group|dictionary_get:week %}
                <div class="card-header d-flex flex-wrap justify-content-between align-items-center">
                    <h5 style="margin-bottom: 0">
                        KW {{ week|date:"W" }} {% translate 'starting' %} {{ week }},
                        {% translate 'Week ' %}{{ week_group.name }}
                    </h5>
                    <div class="d-flex flex-wrap align-items-end align-items-center">
                        <div class="d-inline-flex align-items-baseline p-2 ">
                            <label for="date-from" class="form-label pe-2">{% translate "From" %}</label>
                            <input id="date-from"
                                   type="date"
                                   value="{{ date_from }}"
                                   class="form-control" />
                        </div>
                        <div class="d-inline-flex align-items-baseline p-2">
                            <label for="date-to" class="form-label pe-2">{% translate "To" %}</label>
                            <input id="date-to" type="date" value="{{ date_to }}" class="form-control" />
                        </div>
                        <button class="{% tapir_button_link %} btn" onclick="onFilter()">
                            <span class="material-icons">filter_alt</span>{% translate "Filter" %}
                        </button>
                    </div>
                </div>
            {% endwith %}
            <div class="card-body d-flex flex-row flex-wrap gap-2">
                {% for day, shift_infos in shifts_by_day.items %}
                    <div class="d-flex flex-column">
                        <h5 style="text-align: center;">{{ day|date:"l" }}</h5>
                        <h6 style="text-align: center;">
                            {{ day|date:"M d" }}
                            {% if perms.welcomedesk.view %}
                                <a href="{% url 'shifts:shift_day_printable' day|date:'d-m-y' %}"
                                   class="{% tapir_button_link %}">
                                    <span class="material-icons">print</span>
                                </a>
                                <a href="{% url 'shifts:shift_day_cancel' day|date:'d-m-y' %}"
                                   class="{% tapir_button_link_to_action %}">
                                    <span class="material-icons">event_busy</span>
                                </a>
                            {% endif %}
                        </h6>
                        {% for shift in shift_infos %}
                            <!-- a bit of margin so the boxes don't overlap -->
                            <div style="margin: 3px">
                                <a href="{% url 'shifts:shift_detail' shift.pk %}">{% shift_block shift True %}</a>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock content %}

tapir/shifts/templates/shifts/shiftwatch_overview.html
{% extends "shifts/base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load core %}
{% load utils %}
{% load shifts %}
{% block title %}
    {% translate "Recurring Shiftwatch List" %}
{% endblock title %}
{% block head %}
    {{ form.media }}
{% endblock head %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <!-- Recurring Shift Watches Card -->
        <div class="card mb-2">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h5>{% translate "Recurring Shift Watches" %}</h5>
                <div>
                    <a class="{% tapir_button_link_to_action %}"
                       href="{% url 'shifts:create_watch_recurring_shifts' user.pk %}"
                       id="create_recurring_shiftwatch_button">
                        <span class="material-icons">repeat</span>
                        {% translate "Create a rule for recurring Shift Watches" %}
                    </a>
                </div>
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% for recurringshiftwatch in recurringshiftwatches %}
                        <li class="list-group-item">
                            <input type="checkbox"
                                   class="form-check-input"
                                   name="recurringshiftwatch_ids"
                                   value="{{ recurringshiftwatch.id }}">
                            <span class="text-muted me-2">#{{ recurringshiftwatch.id }}</span>
                            {% if recurringshiftwatch.shift_template_group and recurringshiftwatch.weekdays %}
                                {% translate "You are observing all shifts based on the weekdays:" %}
                                <strong>{{ recurringshiftwatch.weekdays|weekday_labels|join:", " }}</strong>
                                {% translate "and the ABCD-Week:" %}
                                <strong>{{ recurringshiftwatch.shift_template_group|join:", " }}</strong>
                            {% elif recurringshiftwatch.shift_template_group %}
                                {% translate "You are observing all shifts based on the ABCD-Week:" %}
                                <strong>{{ recurringshiftwatch.shift_template_group|join:", " }}</strong>
                            {% elif recurringshiftwatch.weekdays %}
                                {% translate "You are observing all shifts on the weekdays:" %}
                                <strong>{{ recurringshiftwatch.weekdays|weekday_labels|join:", " }}</strong>
                            {% elif recurringshiftwatch.shift_templates.all %}
                                {% translate "You are observing all shifts based on the shift templates:" %}
                                <strong>
                                    {% for template in recurringshiftwatch.shift_templates.all %}
                                        {{ template }}
                                        {% if not forloop.last %},{% endif %}
                                    {% endfor %}
                                </strong>
                            {% else %}
                                {% translate "You are not observing any shifts." %}
                            {% endif %}
                            <br>
                            <div style="margin-left: 20px;">
                                <strong>{% translate "Observed changes:" %}</strong>
                                <ul>
                                    {% for status in recurringshiftwatch.staffing_status %}<li>{{ status }}</li>{% endfor %}
                                </ul>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <!-- Shift Watches Card -->
        <div class="card mb-2">
            <div class="card-header">
                <h5>{% translate "Shift Watches" %}</h5>
            </div>
            <div class="card-body">
                {% if shift_watches %}
                    {% with total=shift_watches|length %}
                        <div class="mb-2">
                            <small class="text-muted">{% translate "Total" %} {{ total }}</small>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for shiftwatch in shift_watches|slice:":10" %}
                                <li class="list-group-item">
                                    <input type="checkbox"
                                           name="shiftwatch_ids"
                                           class="form-check-input"
                                           value="{{ shiftwatch.id }}">
                                    {% shiftwatch_display_without_user shiftwatch %}
                                </li>
                            {% empty %}
                            {% endfor %}
                        </ul>
                        {% if total > 10 %}
                            <div class="mt-2">
                                <button class="{% tapir_button_link_to_action %} m-1"
                                        type="button"
                                        data-bs-toggle="collapse"
                                        data-bs-target="#moreShiftWatches"
                                        aria-expanded="false"
                                        aria-controls="moreShiftWatches"
                                        id="toggleMoreShiftWatches">
                                    {% translate "Show more" %}
                                    <span class="material-icons">keyboard_arrow_down</span>
                                </button>
                            </div>
                            <div class="collapse mt-2" id="moreShiftWatches">
                                <ul class="list-group list-group-flush">
                                    {% for shiftwatch in shift_watches|slice:"10:" %}
                                        <li class="list-group-item">
                                            <input type="checkbox" name="shiftwatch_ids" value="{{ shiftwatch.id }}">
                                            {% shiftwatch_display_without_user shiftwatch %}
                                        </li>
                                    {% empty %}
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    {% endwith %}
                {% else %}
                    <div class="alert alert-info" role="alert">
                        {% translate "You will get mail-notifications when shifts you follow change — tailored to the types of updates you choose (e.g., needs help, is full, cancellations)." %}
                        <br>
                        <br>
                        {% translate "You can watch single shifts for changes by selecting a shift " %}
                        <a href="{% url 'shifts:calendar' %}">{% translate "here" %}</a>
                        {% translate " and clicking on the Watch-button" %}.
                    </div>
                {% endif %}
            </div>
        </div>
        <button type="submit" class="{% tapir_button_custom 'outline-danger' %}">
            <span class="material-icons">delete</span>{% translate "Delete Selected" %}
        </button>
    </form>
{% endblock content %}