tapir/coop/urls.py
from django.urls import path

from tapir.coop import views

app_name = "coop"
urlpatterns = [
    path(
        "share/<int:pk>/edit",
        views.ShareOwnershipUpdateView.as_view(),
        name="share_update",
    ),
    path(
        "share/<int:pk>/delete",
        views.ShareOwnershipDeleteView.as_view(),
        name="shareownership_delete",
    ),
    path("user/draft/", views.DraftUserListView.as_view(), name="draftuser_list"),
    path(
        "user/draft/create",
        views.DraftUserCreateView.as_view(),
        name="draftuser_create",
    ),
    path(
        "user/draft/register",
        views.DraftUserRegisterView.as_view(),
        name="draftuser_register",
    ),
    path(
        "user/draft/register/confirm",
        views.DraftUserConfirmRegistrationView.as_view(),
        name="draftuser_confirm_registration",
    ),
    path(
        "user/draft/<int:pk>/edit",
        views.DraftUserUpdateView.as_view(),
        name="draftuser_update",
    ),
    path(
        "user/draft/<int:pk>",
        views.DraftUserDetailView.as_view(),
        name="draftuser_detail",
    ),
    path(
        "user/draft/<int:pk>/delete",
        views.DraftUserDeleteView.as_view(),
        name="draftuser_delete",
    ),
    path(
        "user/draft/<int:pk>/signed_membership_agreement",
        views.mark_signed_membership_agreement,
        name="mark_draftuser_signed_membership_agreement",
    ),
    path(
        "user/draft/<int:pk>/attended_welcome_session",
        views.mark_attended_welcome_session,
        name="mark_draftuser_attended_welcome_session",
    ),
    path(
        "member/<int:pk>/attended_welcome_session",
        views.mark_shareowner_attended_welcome_session,
        name="mark_shareowner_attended_welcome_session",
    ),
    path(
        "user/draft/<int:pk>/membership_agreement",
        views.draftuser_membership_agreement,
        name="draftuser_membership_agreement",
    ),
    path(
        "member/<int:shareowner_pk>/create_shareownerships",
        views.ShareOwnershipCreateMultipleView.as_view(),
        name="share_create_multiple",
    ),
    path(
        "membership_resignation/new",
        views.MembershipResignationCreateView.as_view(),
        name="membership_resignation_create",
    ),
    path(
        "membership_resignation/<int:pk>/edit",
        views.MembershipResignationEditView.as_view(),
        name="membership_resignation_edit",
    ),
    path(
        "membership_resignation/<int:pk>/detail",
        views.MembershipResignationDetailView.as_view(),
        name="membership_resignation_detail",
    ),
    path(
        "membership_resignation/<int:pk>/delete",
        views.MembershipResignationDeleteView.as_view(),
        name="membership_resignation_delete",
    ),
    path(
        "membership_resignation_list",
        views.MembershipResignationList.as_view(),
        name="membership_resignation_list",
    ),
    path(
        "member/<int:shareowner_pk>/create_user",
        views.CreateUserFromShareOwnerView.as_view(),
        name="create_user_from_shareowner",
    ),
    path(
        "user/draft/<int:pk>/draftuser_create_share_owner",
        views.CreateShareOwnerFromDraftUserView.as_view(),
        name="draftuser_create_share_owner",
    ),
    path(
        "member/",
        views.ShareOwnerListView.as_view(),
        name="shareowner_list",
    ),
    path(
        "member/export/mailchimp",
        views.ShareOwnerExportMailchimpView.as_view(),
        name="shareowner_export_mailchimp",
    ),
    path(
        "member/<int:pk>/membership_confirmation",
        views.ShareOwnerMembershipConfirmationFileView.as_view(),
        name="shareowner_membership_confirmation",
    ),
    path(
        "member/<int:pk>/membership_confirmation/send",
        views.send_shareowner_membership_confirmation_welcome_email,
        name="send_shareowner_membership_confirmation_welcome_email",
    ),
    path(
        "member/<int:pk>/",
        views.ShareOwnerDetailView.as_view(),
        name="shareowner_detail",
    ),
    path(
        "member/<int:pk>/edit",
        views.ShareOwnerUpdateView.as_view(),
        name="shareowner_update",
    ),
    path(
        "member/<int:pk>/delete",
        views.ShareOwnerDeleteView.as_view(),
        name="shareowner_delete",
    ),
    path(
        "statistics",
        views.StatisticsView.as_view(),
        name="statistics",
    ),
    path(
        "about",
        views.AboutView.as_view(),
        name="about",
    ),
    path(
        "matching_program",
        views.MatchingProgramListView.as_view(),
        name="matching_program_list",
    ),
    path(
        "member_count_evolution_json",
        views.MemberCountEvolutionJsonView.as_view(),
        name="member_count_evolution_json",
    ),
    path(
        "share_count_evolution_json",
        views.ShareCountEvolutionJsonView.as_view(),
        name="share_count_evolution_json",
    ),
    path(
        "member_age_distribution_json",
        views.MemberAgeDistributionJsonView.as_view(),
        name="member_age_distribution_json",
    ),
    path(
        "payments/list",
        views.IncomingPaymentListView.as_view(),
        name="incoming_payment_list",
    ),
    path(
        "payments/create",
        views.IncomingPaymentCreateView.as_view(),
        name="incoming_payment_create",
    ),
    path(
        "payments/<int:pk>/edit/",
        views.IncomingPaymentEditView.as_view(),
        name="incoming_payment_edit",
    ),
    path(
        "payments/<int:pk>/delete/",
        views.IncomingPaymentDeleteView.as_view(),
        name="incoming_payment_delete",
    ),
    path(
        "new_members_json_view",
        views.MemberStatusUpdatesJsonView.as_view(),
        name="member_status_updates_json_view",
    ),
    path(
        "new_members_csv_view",
        views.member_status_updates_csv_view,
        name="member_status_updates_csv_view",
    ),
    path(
        "active_members_with_account_at_end_of_month_csv_view",
        views.active_members_with_account_at_end_of_month_csv_view,
        name="active_members_with_account_at_end_of_month_csv_view",
    ),
    path(
        "number_of_co_purchasers_json_view",
        views.NumberOfCoPurchasersJsonView.as_view(),
        name="number_of_co_purchasers_json_view",
    ),
    path(
        "number_of_co_purchasers_csv_view",
        views.number_of_co_purchasers_csv_view,
        name="number_of_co_purchasers_csv_view",
    ),
    path(
        "membership_pauses",
        views.MembershipPauseListView.as_view(),
        name="membership_pauses",
    ),
    path(
        "membership_pause/new",
        views.MembershipPauseCreateView.as_view(),
        name="membership_pause_create",
    ),
    path(
        "membership_pause/edit/<int:pk>",
        views.MembershipPauseEditView.as_view(),
        name="membership_pause_edit",
    ),
    path(
        "management",
        views.MemberManagementView.as_view(),
        name="management",
    ),
    path(
        "create/general_account/",
        views.CreateGeneralTapirAccountView.as_view(),
        name="create_general_account",
    ),
    path(
        "general_accounts",
        views.GeneralTapirAccountsListView.as_view(),
        name="general_accounts_list",
    ),
    path(
        "member_self_registration",
        views.MemberSelfRegistrationTemplateView.as_view(),
        name="member_self_registration",
    ),
    path(
        "member_self_register",
        views.MemberSelfRegisterApiView.as_view(),
        name="member_self_register",
    ),
]

tapir/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import generic

from tapir.settings import ENABLE_SILK_PROFILING

urlpatterns = [
    path("", generic.RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL)),
    path("admin/", admin.site.urls),
    path("accounts/", include("tapir.accounts.urls")),
    path("shifts/", include("tapir.shifts.urls")),
    path("rizoma/", include("tapir.rizoma.urls")),
    path("coop/", include("tapir.coop.urls")),
    path("log/", include("tapir.log.urls")),
    path("core/", include("tapir.core.urls")),
    path("statistics/", include("tapir.statistics.urls")),
    path("welcomedesk/", include("tapir.welcomedesk.urls")),
    path("financingcampaign/", include("tapir.financingcampaign.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if ENABLE_SILK_PROFILING:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

tapir/coop/views/incoming_payments.py
import django_filters
import django_tables2
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.db import transaction
from django.db.models import Q
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django_filters.views import FilterView
from django_tables2 import SingleTableView

from tapir.accounts.models import TapirUser
from tapir.coop.forms import IncomingPaymentForm
from tapir.coop.models import (
    IncomingPayment,
    ShareOwner,
    CreatePaymentLogEntry,
    UpdateIncomingPaymentLogEntry,
    DeleteIncomingPaymentLogEntry,
)
from tapir.core.config import TAPIR_TABLE_CLASSES, TAPIR_TABLE_TEMPLATE
from tapir.core.views import TapirFormMixin
from tapir.log.util import freeze_for_log
from tapir.log.views import UpdateViewLogMixin
from tapir.settings import (
    PERMISSION_COOP_VIEW,
    PERMISSION_ACCOUNTING_MANAGE,
    PERMISSION_ACCOUNTING_VIEW,
    PERMISSION_COOP_ADMIN,
)
from tapir.utils.filters import ShareOwnerModelChoiceFilter, TapirUserModelChoiceFilter
from tapir.utils.forms import DateFromToRangeFilterTapir
from tapir.utils.user_utils import UserUtils


class IncomingPaymentTable(django_tables2.Table):
    class Meta:
        model = IncomingPayment
        template_name = TAPIR_TABLE_TEMPLATE
        fields = [
            "id",
            "paying_member",
            "credited_member",
            "amount",
            "payment_date",
            "creation_date",
            "comment",
            "created_by",
        ]
        order_by = "-payment_date"
        attrs = {"class": TAPIR_TABLE_CLASSES}

    id = django_tables2.Column(verbose_name=_("Payment ID"))
    actions = django_tables2.TemplateColumn(
        template_name="coop/incoming_payments_actions_column.html",
        verbose_name="Actions",
        orderable=False,
        exclude_from_export=True,
        visible=False,
    )

    def before_render(self, request):
        self.request = request
        if request.user.has_perm(PERMISSION_COOP_ADMIN):
            self.columns.show("actions")

    def render_id(self, value, record: IncomingPayment):
        return f"#{record.id}"

    def render_member(self, logged_in_member: TapirUser, other_member: ShareOwner):
        if getattr(
            logged_in_member, "share_owner", None
        ) == other_member or logged_in_member.has_perm(PERMISSION_ACCOUNTING_VIEW):
            other_member = other_member.get_info()
            return UserUtils.build_html_link_for_viewer(other_member, logged_in_member)
        return _("Other member")

    def render_paying_member(self, value, record: IncomingPayment):
        return self.render_member(self.request.user, record.paying_member)

    def render_credited_member(self, value, record: IncomingPayment):
        return self.render_member(self.request.user, record.credited_member)

    def render_created_by(self, value, record: IncomingPayment):
        return self.render_member(self.request.user, record.created_by.share_owner)

    def render_payment_date(self, value, record: IncomingPayment):
        return record.payment_date.strftime("%d.%m.%Y")

    def render_creation_date(self, value, record: IncomingPayment):
        return record.creation_date.strftime("%d.%m.%Y")


class IncomingPaymentFilter(django_filters.FilterSet):
    class Meta:
        model = IncomingPayment
        fields = []

    payment_date = DateFromToRangeFilterTapir(
        field_name="payment_date",
    )
    creation_date = DateFromToRangeFilterTapir(
        field_name="creation_date",
    )

    paying_member = ShareOwnerModelChoiceFilter()
    credited_member = ShareOwnerModelChoiceFilter()
    created_by = TapirUserModelChoiceFilter()


class IncomingPaymentListView(LoginRequiredMixin, FilterView, SingleTableView):
    table_class = IncomingPaymentTable
    model = IncomingPayment
    template_name = "coop/incoming_payment_list.html"

    filterset_class = IncomingPaymentFilter

    def get_queryset(self):
        queryset = IncomingPayment.objects.all()
        if not self.request.user.has_perm(PERMISSION_ACCOUNTING_VIEW):
            tapir_user: TapirUser = self.request.user
            logged_in_share_owner = tapir_user.share_owner
            return queryset.filter(
                Q(paying_member=logged_in_share_owner)
                | Q(credited_member=logged_in_share_owner)
            )
        queryset = queryset.prefetch_related(
            "credited_member__user", "paying_member__user", "created_by__share_owner"
        )
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["enable_filter"] = self.request.user.has_perm(PERMISSION_COOP_VIEW)
        return context_data


class IncomingPaymentCreateView(
    LoginRequiredMixin, PermissionRequiredMixin, TapirFormMixin, generic.CreateView
):
    permission_required = PERMISSION_ACCOUNTING_MANAGE
    model = IncomingPayment
    form_class = IncomingPaymentForm

    def get_success_url(self):
        return reverse("coop:incoming_payment_list")

    def form_valid(self, form):
        with transaction.atomic():
            payment: IncomingPayment = form.instance
            payment.creation_date = timezone.now().date()
            payment.created_by = self.request.user
            payment.save()
            CreatePaymentLogEntry().populate(
                actor=self.request.user,
                share_owner=form.cleaned_data["credited_member"],
                amount=form.cleaned_data["amount"],
                payment_date=form.cleaned_data["payment_date"],
            ).save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["page_title"] = _("Register payment")
        context["card_title"] = _("Register a new incoming payment")
        return context


class IncomingPaymentEditView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    TapirFormMixin,
    UpdateViewLogMixin,
    generic.UpdateView,
):
    permission_required = PERMISSION_COOP_ADMIN
    model = IncomingPayment
    form_class = IncomingPaymentForm

    def get_success_url(self):
        return reverse("coop:incoming_payment_list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["page_title"] = _("Edit payment")
        context["card_title"] = _("Edit payment")
        return context

    def form_valid(self, form):
        messages.success(self.request, _("Payment updated."))
        new_frozen = freeze_for_log(form.instance)
        if self.old_object_frozen != new_frozen:
            UpdateIncomingPaymentLogEntry().populate(
                old_frozen=self.old_object_frozen,
                new_frozen=new_frozen,
                share_owner=form.instance.paying_member,
                actor=self.request.user,
            ).save()
        return super().form_valid(form)


class IncomingPaymentDeleteView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView
):
    permission_required = PERMISSION_COOP_ADMIN
    model = IncomingPayment
    template_name = "coop/confirm_delete_incoming_payment.html"

    def get_success_url(self):
        return reverse("coop:incoming_payment_list")

    def form_valid(self, form):
        result = super().form_valid(form)
        messages.success(self.request, _("Payment deleted"))
        DeleteIncomingPaymentLogEntry().populate(
            share_owner=self.object.paying_member,
            actor=self.request.user,
            model=self.object,
        ).save()
        return result

tapir/coop/templates/coop/tags/member_status_colored_text_tag.html
<span class="text-{{ color }}">{{ text }}</span>

tapir/coop/templates/coop/tags/user_coop_share_ownership_list_tag.html
{% load static %}
{% load coop %}
{% load i18n %}
{% load core %}
<div class="card mb-2" id="user_coop_info_card">
    <h5 class="card-header d-flex justify-content-between align-items-center flex-wrap gap-2">
        {% if share_owner and not share_owner.is_soft_deleted %}
            <span>
                {% blocktranslate with coop_share_owner_id=share_owner.id %}
                    Member #{{ coop_share_owner_id }}
                {% endblocktranslate %}
            </span>
            {% if perms.accounts.manage or perms.group.manage %}
                <span class="d-flex justify-content-end flex-fill flex-wrap gap-2">
                    {% if perms.accounts.manage %}
                        <a class="{% tapir_button_link %}"
                           href="{% url 'coop:shareowner_membership_confirmation' share_owner.pk %}">
                            <span class="material-icons">file_present</span>{% translate 'Membership confirmation' %}
                        </a>
                        <a class="{% tapir_button_link_to_action %}"
                           href="{% url 'coop:shareowner_update' share_owner.pk %}"
                           id="share_owner_edit_button">
                            <span class="material-icons">edit</span>{% translate 'Edit' %}
                        </a>
                    {% endif %}
                    {% if perms.group.manage %}
                        <a class="{% tapir_button_custom 'outline-danger' %}"
                           href="{% url 'coop:shareowner_delete' share_owner.pk %}"
                           id="share_owner_delete_button">
                            <span class="material-icons">delete</span>{% translate 'Delete' %}
                        </a>
                    {% endif %}
                </span>
            {% endif %}
        {% endif %}
    </h5>
    <div class="card-body">
        {% if share_owner and not share_owner.is_soft_deleted %}
            <div class="row m-1">
                <div class="col-12 col-sm-5 fw-bold text-sm-end">{% translate "Status" %}:</div>
                <div class="col-12 col-sm-7" id="share_owner_status">
                    {% member_status_colored_text share_owner %}
                    {% if share_owner.get_membership_start_date %}
                        {% blocktranslate with start_date=share_owner.get_membership_start_date|date:"d.m.Y" %}
                            (membership starting {{ start_date }})
                        {% endblocktranslate %}
                    {% endif %}
                    {% if share_owner.get_membership_end_date %}
                        {% blocktranslate with end_date=share_owner.get_membership_end_date|date:"d.m.Y" %}
                            (membership ending {{ end_date }})
                        {% endblocktranslate %}
                    {% endif %}
                </div>
            </div>
            {% if object.ratenzahlung %}
                <div class="row m-1">
                    <div class="col-12 col-sm-3 fw-bold text-sm-end">{% translate "Ratenzahlung" %}:</div>
                    <div class="col-12 col-sm-9" id="share_owner_email">Yes</div>
                </div>
            {% endif %}
            <div class="row m-1">
                <div class="col-12 col-sm-5 fw-bold text-sm-end">{% translate "Welcome Session" %}:</div>
                <div class="col-12 col-sm-7">
                    {% if share_owner.attended_welcome_session %}
                        <span class="text-success">{% translate "Attended" %}</span>
                    {% else %}
                        <span class="text-warning">{% translate "Pending" %}</span>
                        {% if perms.accounts.manage %}
                            <form style="display: inline"
                                  method="post"
                                  action="{% url 'coop:mark_shareowner_attended_welcome_session' share_owner.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="{% tapir_button_action %} btn-sm ml-3">
                                    <span class="material-icons">check</span>{% translate "Mark Attended" %}
                                </button>
                            </form>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="row m-1">
                <div class="col-12 col-sm-5 fw-bold text-sm-end">
                    <a data-bs-toggle="collapse" href="#shares-table">{% translate "Owned shares" %}:</a>
                </div>
                <div class="col-12 col-sm-7">
                    <span id="share_owner_num_shares">{{ share_owner.num_shares }}</span>
                </div>
            </div>
            <div class="collapse" id="shares-table">
                <table class="table"
                       aria-label="{% translate 'List of shares owned by this member' %}">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{% translate "Starts at" %}</th>
                            <th scope="col">{% translate "Ends at" %}</th>
                            <th scope="col">{% translate "Status" %}</th>
                            {% if perms.coop.manage %}
                                <th scope="col">{% translate 'Edit' %}</th>
                            {% endif %}
                        </tr>
                    </thead>
                    {% for o in share_owner.share_ownerships.all %}
                        <tr>
                            <td>{{ o.id }}</td>
                            <td>{{ o.start_date }}</td>
                            <td>
                                {% if o.end_date %}{{ o.end_date }}{% endif %}
                            </td>
                            <td>
                                {% if o.is_active %}
                                    <span class="text-success">{% translate "Active" %}</span>
                                {% else %}
                                    <span class="text-danger">{% translate "Sold or future" %}</span>
                                {% endif %}
                            </td>
                            {% if perms.coop.manage %}
                                <td>
                                    <a class="{% tapir_button_link_to_action %} btn-sm"
                                       href="{% url 'coop:share_update' o.pk %}">
                                        <span class="material-icons">edit</span>
                                        {% translate "Edit" %}
                                    </a>
                                    {% if perms.coop.admin %}
                                        <div class="dropdown share_ownership_delete_dropdown">
                                            <a class="{% tapir_button_link %} btn-sm dropdown-toggle"
                                               href="#"
                                               data-bs-toggle="dropdown">
                                                <span class="material-icons">more_horiz</span>&nbsp;
                                            </a>
                                            <div class="dropdown-menu dropdown-menu-right" style="min-width: 20rem;">
                                                <!-- white-space: normal; to make the long text wrap -->
                                                <a class="form-inline"
                                                   href="{% url 'coop:shareownership_delete' o.pk %}">
                                                    <span class="dropdown-item " style="white-space: normal" href="#">
                                                        <span class="text-danger">{% translate "Delete" %}</span>
                                                        <br />
                                                        <small class="text-muted">
                                                            {% blocktrans %}
                                                            Only use this to correct mistakes, i.e. if the share was
                                                            erroneously
                                                            entered into the system and the person never actually
                                                            bought it. If the person simply sold their share back to the
                                                            coop, please mark the share as sold instead.
                                                        {% endblocktrans %}
                                                        </small>
                                                    </span>
                                                </a>
                                            </div>
                                        </div>
                                    {% endif %}
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
                {% if perms.accounts.manage %}
                    <div class="d-flex justify-content-end">
                        <a class="ml-auto {% tapir_button_link_to_action %}"
                           href="{% url 'coop:share_create_multiple' share_owner.pk %}">
                            <span class="material-icons">add_circle_outline</span>
                            {% translate "Add Shares" %}
                        </a>
                    </div>
                {% endif %}
            </div>
            <div class="row m-1">
                <div class="col-12 col-sm-5 fw-bold text-sm-end">
                    <a href="{% url 'coop:incoming_payment_list' %}?credited_member={{ share_owner.pk }}">{% translate "Payments" %}:</a>
                </div>
                <div class="col-12 col-sm-7">
                    <span>{{ share_owner.get_currently_paid_amount }} / {{ share_owner.get_total_expected_payment }} €</span>
                </div>
            </div>
            <div class="row m-1">
                <div class="col-12 col-sm-5 fw-bold text-sm-end">{% translate "Ratenzahlung" %}:</div>
                <div class="col-12 col-sm-7">{{ share_owner.ratenzahlung|yesno:_("Yes,No") }}</div>
            </div>
            <div class="row m-1">
                <div class="col-12 col-sm-5 fw-bold text-sm-end">{% translate "Willing to gift a share" %}:</div>
                <div class="col-12 col-sm-7">{{ share_owner.willing_to_gift_a_share|yesno:_("Yes,No") }}</div>
            </div>
            {% if perms.accounts.manage %}
                <div class="d-flex align-items-end flex-column-reverse">
                    <form class="p-2"
                          method="post"
                          action="{% url 'coop:send_shareowner_membership_confirmation_welcome_email' share_owner.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="{% tapir_button_action %} align-self-right">
                            <span class="material-icons">send</span>{% translate 'Send membership confirmation email' %}
                        </button>
                    </form>
                </div>
            {% endif %}
        {% else %}
            {% translate "User is not a cooperative member." %}
        {% endif %}
    </div>
</div>