tapir/rizoma/urls.py
from django.urls import path

from tapir.rizoma import views

app_name = "rizoma"
urlpatterns = [
  path(
        "shifts/all",
        views.RizomaAllShiftsView.as_view(),
        name="all_shifts",
    ),
]

tapir/shifts/urls.py
from django.urls import path

from tapir.shifts import views

app_name = "shifts"
urlpatterns = [
    path("shift/<int:pk>/", views.ShiftDetailView.as_view(), name="shift_detail"),
    path(
        "shift/<int:pk>/printable",
        views.ShiftDetailView.as_view(
            template_name="shifts/shift_detail_printable.html"
        ),
        name="shift_detail_printable",
    ),
    path(
        "shift/<str:day>/day_printable",
        views.ShiftDayPrintableView.as_view(),
        name="shift_day_printable",
    ),
    path(
        "shift/<str:day>/day_cancel",
        views.CancelDayShiftsView.as_view(),
        name="shift_day_cancel",
    ),
    path(
        "shift/<int:pk>/edit",
        views.EditShiftView.as_view(),
        name="shift_edit",
    ),
    path(
        "shift/<int:pk>/delete",
        views.DeleteShiftView.as_view(),
        name="shift_delete",
    ),
    path(
        "shift_template/<int:pk>/edit",
        views.EditShiftTemplateView.as_view(),
        name="shift_template_edit",
    ),
    path(
        "shift_template/create",
        views.ShiftTemplateCreateView.as_view(),
        name="shift_template_create",
    ),
    path(
        "shift_attendance/<int:pk>/<int:state>",
        views.UpdateShiftAttendanceStateView.as_view(),
        name="update_shift_attendance_state",
    ),
    path(
        "shift_attendance_form/<int:pk>/<int:state>",
        views.UpdateShiftAttendanceStateWithFormView.as_view(),
        name="update_shift_attendance_state_with_form",
    ),
    path(
        "shifttemplate/<int:pk>",
        views.ShiftTemplateDetail.as_view(),
        name="shift_template_detail",
    ),
    path(
        "shift_template_duplicate/<int:shift_pk>/create",
        views.ShiftTemplateDuplicateView.as_view(),
        name="shift_template_duplicate",
    ),
    path(
        "shifttemplate/overview",
        views.ShiftTemplateOverview.as_view(),
        name="shift_template_overview",
    ),
    path(
        "slottemplate/<int:slot_template_pk>/register",
        views.RegisterUserToShiftSlotTemplateView.as_view(),
        name="slottemplate_register",
    ),
    path(
        "shiftslot/<int:slot_pk>/register/",
        views.RegisterUserToShiftSlotView.as_view(),
        name="slot_register",
    ),
    path(
        "shift_attendance_template/<int:pk>/delete",
        views.shift_attendance_template_delete,
        name="shift_attendance_template_delete",
    ),
    path(
        "calendar",
        views.ShiftCalendarView.as_view(),
        name="calendar",
    ),
    path(
        "shift_user_data/<int:pk>",
        views.EditShiftUserDataView.as_view(),
        name="edit_shift_user_data",
    ),
    path(
        "group_calendar",
        views.ShiftTemplateGroupCalendar.as_view(),
        name="shift_template_group_calendar",
    ),
    path(
        "group_calendar/<int:year>",
        views.ShiftTemplateGroupCalendar.as_view(),
        name="shift_template_group_calendar",
    ),
    path(
        "group_calendar/<int:year>/pdf",
        views.ShiftTemplateGroupCalendarAsPdf.as_view(),
        name="calendarpdf",
    ),
    path(
        "shift_account_entry/log/<int:user_pk>",
        views.UserShiftAccountLog.as_view(),
        name="user_shift_account_log",
    ),
    path(
        "shift_account_entry/create/<int:user_pk>",
        views.CreateShiftAccountEntryView.as_view(),
        name="create_shift_account_entry",
    ),
    path(
        "shift_exemption/create/<int:shift_user_data_pk>",
        views.CreateShiftExemptionView.as_view(),
        name="create_shift_exemption",
    ),
    path(
        "shift_exemption/<int:pk>/edit",
        views.EditShiftExemptionView.as_view(),
        name="edit_shift_exemption",
    ),
    path(
        "shift_exemption",
        views.ShiftExemptionListView.as_view(),
        name="shift_exemption_list",
    ),
    path(
        "members_on_alert",
        views.MembersOnAlertView.as_view(),
        name="members_on_alert",
    ),
    path(
        "shift/<int:pk>/cancel",
        views.CancelShiftView.as_view(),
        name="cancel_shift",
    ),
    path(
        "shift/create",
        views.ShiftCreateView.as_view(),
        name="create_shift",
    ),
    path(
        "shift/<int:shift_pk>/slot/create",
        views.ShiftSlotCreateView.as_view(),
        name="create_slot",
    ),
    path(
        "shift_template/<int:shift_pk>/slot_template/create",
        views.ShiftSlotTemplateCreateView.as_view(),
        name="create_slot_template",
    ),
    path(
        "slot/<int:pk>/edit",
        views.ShiftSlotEditView.as_view(),
        name="edit_slot",
    ),
    path(
        "slot_template/<int:pk>/edit",
        views.ShiftSlotTemplateEditView.as_view(),
        name="edit_slot_template",
    ),
    path(
        "management",
        views.ShiftManagementView.as_view(),
        name="shift_management",
    ),
    path(
        "run_freeze_checks_manually",
        views.RunFreezeChecksManuallyView.as_view(),
        name="run_freeze_checks_manually",
    ),
    path(
        "generate_shifts_manually",
        views.GenerateShiftsManuallyView.as_view(),
        name="generate_shifts_manually",
    ),
    path(
        "convert_shift_exemption_to_membership_pause/<int:pk>",
        views.ConvertShiftExemptionToMembershipPauseView.as_view(),
        name="convert_shift_exemption_to_membership_pause",
    ),
    path(
        "solidarity_shift_used/<int:pk>",
        views.SolidarityShiftUsed.as_view(),
        name="solidarity_shift_used",
    ),
    path(
        "solidarity_shift_given/<int:pk>",
        views.SolidarityShiftGiven.as_view(),
        name="solidarity_shift_given",
    ),
    path(
        "solidarity_shifts",
        views.SolidarityShiftsView.as_view(),
        name="solidarity_shifts",
    ),
    path(
        "solidarity_shifts/gifted_solidarity_shifts_json",
        views.GiftedSolidarityShiftsJsonView.as_view(),
        name="gifted_solidarity_shifts_json",
    ),
    path(
        "solidarity_shifts/used_solidarity_shifts_json",
        views.UsedSolidarityShiftsJsonView.as_view(),
        name="used_solidarity_shifts_json",
    ),
    path(
        "attendance/<int:pk>/custom_time",
        views.UpdateShiftAttendanceCustomTimeView.as_view(),
        name="attendance_custom_time",
    ),
    path(
        "attendance_template/<int:pk>/custom_time",
        views.UpdateShiftAttendanceTemplateCustomTimeView.as_view(),
        name="attendance_template_custom_time",
    ),
    path(
        "watch_shift/<int:shift>/", views.WatchShiftView.as_view(), name="watch_shift"
    ),
    path(
        "unwatch_shift/<int:shift>/",
        views.UnwatchShiftView.as_view(),
        name="unwatch_shift",
    ),
    path(
        "create_watch_recurring_shifts/<int:pk>",
        views.CreateRecurringShiftWatchView.as_view(),
        name="create_watch_recurring_shifts",
    ),
    path(
        "shiftwatch_overview/<int:pk>",
        views.RecurringShiftwatchListView.as_view(),
        name="shiftwatch_overview",
    ),
]

tapir/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import generic

from tapir.settings import ENABLE_SILK_PROFILING

urlpatterns = [
    path("", generic.RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL)),
    path("admin/", admin.site.urls),
    path("accounts/", include("tapir.accounts.urls")),
    path("shifts/", include("tapir.shifts.urls")),
    path("rizoma/", include("tapir.rizoma.urls")),
    path("coop/", include("tapir.coop.urls")),
    path("log/", include("tapir.log.urls")),
    path("core/", include("tapir.core.urls")),
    path("statistics/", include("tapir.statistics.urls")),
    path("welcomedesk/", include("tapir.welcomedesk.urls")),
    path("financingcampaign/", include("tapir.financingcampaign.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if ENABLE_SILK_PROFILING:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

tapir/rizoma/models.py
from django.db import models

from tapir.coop.models import ShareOwner


class RizomaMemberData(models.Model):
    photo_id = models.CharField(null=True, max_length=255)
    share_owner = models.OneToOneField(
        ShareOwner,
        null=False,
        on_delete=models.CASCADE,
        related_name="rizoma_member_data",
    )

tapir/rizoma/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
import datetime
from django.utils import timezone
from django.conf import settings
from collections import OrderedDict
from tapir.shifts.models import Shift
from tapir.shifts.models import ShiftSlot
from tapir.shifts.templatetags.shifts import shift_name_as_class
from django.utils.translation import gettext_lazy as _
from tapir.rizoma.utils import format_shift_for_template
from tapir.shifts.models import ShiftAccountEntry
from datetime import date, timedelta
from django.urls import reverse


# based on the ShiftCalendarView in shifts/views/calendars.py
class RizomaAllShiftsView(LoginRequiredMixin, TemplateView):
    template_name = "rizoma/all_shifts.html"
    DATE_FORMAT = "%Y-%m-%d"

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)

        try:
            date_from = (
                datetime.datetime.strptime(
                    self.request.GET["date_from"], self.DATE_FORMAT
                ).date()
                if "date_from" in self.request.GET.keys()
                else timezone.now().date()
            )
            date_to = (
                datetime.datetime.strptime(
                    self.request.GET["date_to"], self.DATE_FORMAT
                ).date()
                if "date_to" in self.request.GET.keys()
                else date_from + datetime.timedelta(days=7)
            )
        except:
            date_from = timezone.now().date()
            date_to = date_from + datetime.timedelta(days=7)

        context_data["date_from"] = date_from.strftime(self.DATE_FORMAT)
        context_data["date_to"] = date_to.strftime(self.DATE_FORMAT)

        context_data["nb_days_for_self_unregister"] = int(
            settings.NB_HOURS_FOR_SELF_UNREGISTER / 24
        )
        # Because the shift views show a lot of shifts,
        # we preload all related objects to avoid doing many database requests.
        shifts = (
            Shift.objects.prefetch_related("slots")
            .prefetch_related("slots__attendances")
            .prefetch_related("slots__attendances__user")
            .prefetch_related("slots__slot_template")
            .prefetch_related("slots__slot_template__attendance_template")
            .prefetch_related("slots__slot_template__attendance_template__user")
            .prefetch_related("shift_template")
            .prefetch_related("shift_template__group")
            .filter(
                start_time__gte=date_from,
                start_time__lt=date_to + datetime.timedelta(days=1),
                deleted=False,
            )
            .order_by("start_time")
        )

        distinct_slot_names = set(slot.slot_template.name for shift in shifts for slot in shift.slots.all())

        # A dict containing the shifts times and the shifts names for each day
        shifts_infos_by_day = OrderedDict()
        for shift in shifts:
            shift_day = shift.start_time.date()

            if shifts_infos_by_day.get(shift_day) is None:
                shifts_infos_by_day[shift_day] = {
                    "times": [],
                    "shifts_types": [],
                    "shifts": [],
                }

            infos = shifts_infos_by_day[shift_day]
            shift_times = {
                "start_time": shift.start_time,
                "end_time": shift.end_time,
            }

            has_this_shift_time = any(t['start_time'] == shift_times['start_time'] and t['end_time'] == shift_times['end_time'] for t in infos["times"])
            if not has_this_shift_time:
                shifts_infos_by_day[shift_day]["times"].append(shift_times)

            shifts_infos_by_day[shift_day]["shifts_types"] = distinct_slot_names

            # browser all the slot's names and add them to the types list
            # for slot in shift.slots.all():
            #     if slot.name not in infos["shifts_types"]:
            #         shifts_infos_by_day[shift_day]["shifts_types"].append(slot.name)

            shifts_infos_by_day[shift_day]["shifts"].append(format_shift_for_template(shift, False))

        context_data["shifts_infos_by_day"] = shifts_infos_by_day

        context_data["week_ranges"] = get_week_ranges({
            "start": date_from,
            "end": date_to,
        })
        # Find the selected week range in week_ranges
        current_week_range = next(
            (
                week
                for week in context_data["week_ranges"]
                if week["start"] == date_from and week["end"] == date_to
            ),
            None
        )
        context_data["current_week_range"] = current_week_range if current_week_range is not None else {
            "start": date_from,
            "end": date_to,
        }
        context_data["next_week_range"] = {
            "start": context_data["current_week_range"].get("start") + timedelta(days=7),
            "end": context_data["current_week_range"].get("end") + timedelta(days=7),
        }
        context_data["previous_week_range"] = {
            "start": context_data["current_week_range"].get("start") - timedelta(days=7),
            "end": context_data["current_week_range"].get("end") - timedelta(days=7),
        }

        return context_data


def get_week_ranges(current_week_range):
        if current_week_range.get("start") and current_week_range.get("end"):
            current_start = current_week_range.get("start")
            current_end = current_week_range.get("end")
        else:
            current_start = timezone.now().date()
            current_end = timezone.now().date() + timedelta(days=6)

        today = date.today()
        # Find the most recent Monday (or today if today is Monday)
        start_of_week = today - timedelta(days=today.weekday())
        week_ranges = []
        for i in range(10):
            week_start = start_of_week + timedelta(weeks=i)
            week_end = week_start + timedelta(days=6)
            week_ranges.append({
                "start": week_start,
                "end": week_end,
                "url": reverse("shifts:calendar") + f"?date_from={week_start}&date_to={week_end}",
                "is_selected": week_start <= current_start and week_end >= current_end,
            })
        # Pass week_ranges to the template context
        return week_ranges

rizoma/templates/shifts/shift_template_group_calendar.html
{% extends "shifts/base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}
{% load static %}
{% load shifts %}
{% load coop %}
{% load core %}
{% block title %}
    {% translate 'ABCD weeks calendar' %}
{% endblock title %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'shifts/css/calendar.css' %}">
{% endblock head %}
{% block content %}

  <div class="container">
    <div class="card mb-2">
        <h5 class="card-header d-flex justify-content-between align-items-center">
            <span>{% translate 'ABCD weeks calendar' %}</span>
            <span>
                <a class="{% tapir_button_link %} ms-3"
                   href="{% url 'shifts:shift_template_group_calendar' displayed_year|add:-1 %}">
                    <span class="material-icons">arrow_back</span>{{ displayed_year|add:-1 }}
                </a>
                <a class="{% tapir_button_link %} ms-3"
                   href="{% url 'shifts:calendarpdf' displayed_year %}">
                    <span class="material-icons">file_present</span>
                    {{ displayed_year }} {% translate 'as pdf' %}
                </a>
                <a class="{% tapir_button_link %} ms-3"
                   href="{% url 'shifts:shift_template_group_calendar' displayed_year|add:1 %}">
                    {{ displayed_year|add:1 }}<span class="material-icons">arrow_forward</span>
                </a>
            </span>
        </h5>
        <div class="card-body">{{ rendered_calendar }}</div>
    </div>
  </div>
{% endblock content %}

rizoma/templates/shifts/shift_template_overview.html
{% extends "shifts/base.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% load shifts %}
{% load i18n %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'shifts/css/shifts.css' %}">
    <script src="{% static 'shifts/ShiftFiltersManager.js' %}?version=2" defer></script>
{% endblock head %}
{% block title %}
    {% translate 'ABCD week-plan' %}
{% endblock title %}
{% block content %}
    <div class="container">
        <h1 class="h1">
            {{ _("All Shifts") }}
        </h1>
        <div class="tab-links mb-4">
            <a href="{% url 'rizoma:all_shifts' %}" class="tab-link">{{_("Upcoming")}}</a>
            <span class="tab-link tab-link active">{{_("Recurring")}}</span>
        </div>

        <div class="card-group mb-2">
            <div class="card">
                <h5 class="card-header">
                    {% get_current_week_group as group %}
                    {% translate "ABCD schedule overview, current week: " %}{{ group.name }}
                </h5>
                <div class="card-body">
                    {% blocktranslate %}
                        <p>This is the ABCD shiftplan. It repeats every four weeks. That's why you see only weekdays
                            (Monday, Tuesday...) and the week (A,B,C or D), instead of specific dates (e.g. 23.8.2021).
                            To see the date of your next shift, please go to your profile.</p>
                        <p>If you would like to change your regular ABCD shift, please contact the Member Office.</p>
                    {% endblocktranslate %}
                </div>
            </div>
            {% shift_filters %}
        </div>

        <div class="card mb-2">
            <table class="table"
                id="repeated-shift-overview-table"
                aria-label="{% translate 'Calendar of ABCD shifts' %}">
                <thead>
                    <tr>
                        <th class="text-center">Time</th>
                        {% for group in shift_template_groups %}
                            <th class="text-center">{% translate 'Week ' %}{{ group }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for day, day_group in day_groups.items %}
                        <tr>
                            <td></td>
                            <td class="text-center" colspan="{{ shift_template_groups|length }}">
                                <h4 class="fw-bold">{{ day }}</h4>
                            </td>
                        </tr>
                        {% for time, time_group in day_group.items %}
                            <tr>
                                <td>{{ time }}</td>
                                {% for template_group_group in time_group.values %}
                                    <td>
                                        <div class="d-flex flex-column" style="gap: 10px;">
                                            {% for shift_template in template_group_group.values %}
                                                {% if shift_template != None %}
                                                    {% block shift_template %}
                                                        <a href="    {{ shift_template.get_absolute_url }}{% if selected_user %}?selected_user={{ selected_user.pk|urlencode }}{% endif %}">
                                                            {% shift_template_block shift_template %}
                                                        </a>
                                                    {% endblock shift_template %}
                                                {% else %}
                                                    <div class="shift-template-block-container"></div>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}